export enum Themes {
  LightSkyBlue = "lightskyblue",
  Violet = "violet",
  Lime = "lime",
  Gold = "gold",
  Thistle = "thistle",
  White = "white",
  Chocolate = "chocolate",
  Crimson = "crimson",
  CornflowerBlue = "cornflowerblue",
  DarkSalmon = "darksalmon",
  Indigo = "indigo",
  PaleVioletRed = "palevioletred",
  Sienna = "sienna",
  Teal = "teal",
  Tomato = "tomato",
}
